apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
spec:
  secretName: prometheus-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.kubernetes.home
