- name: Create the docker-compose directory if it does not exist
  ansible.builtin.file:
    path: "{{ docker_compose_rootdir }}/{{ docker_compose_projectname }}"
    state: directory
    mode: '0755'
- name: Create bind mount directories
  ansible.builtin.file:
    path: "{{ docker_compose_rootdir }}/{{ docker_compose_projectname }}/{{ item.name }}"
    state: directory
    mode: "{{ item.folder_mode | default('0755') }}"
    owner: "{{ docker_compose_files_owner }}"
    group: "{{ docker_compose_files_group }}"
  loop: "{{ docker_compose_create_dirs }}"
- name: Copy any static files necessary
  ansible.builtin.copy:
    src: "{{ docker_compose_projectname }}/{{ item.name }}/"   # Note the / at the end !
    dest: "{{ docker_compose_rootdir }}/{{ docker_compose_projectname }}/{{ item.name }}"
    mode: "{{ item.file_mode | default('0644') }}"
    owner: "{{ docker_compose_files_owner }}"
    group: "{{ docker_compose_files_group }}"
    directory_mode: "{{ item.folder_mode | default('0755') }}"
  loop: "{{ docker_compose_static_files_copy }}"
- name: Make sure destination dir exists for template files
  ansible.builtin.file:
    path: "{{ docker_compose_rootdir }}/{{ docker_compose_projectname }}/{{ item.name | dirname }}"
    state: directory
    mode: "{{ item.folder_mode | default('0755') }}"
    owner: "{{ docker_compose_files_owner }}"
    group: "{{ docker_compose_files_group }}"
  loop: "{{ docker_compose_template_files_copy }}"
- name: Copy any template files necessary
  ansible.builtin.template:
    src: "{{ docker_compose_projectname }}/{{ item.name }}.j2"
    dest: "{{ docker_compose_rootdir }}/{{ docker_compose_projectname }}/{{ item.name }}"
    mode: "{{ item.file_mode | default('0644') }}"
    owner: "{{ docker_compose_files_owner }}"
    group: "{{ docker_compose_files_group }}"
  loop: "{{ docker_compose_template_files_copy }}"
- name: Copy docker compose file
  ansible.builtin.template:
    src: "{{ docker_compose_projectname }}_docker_compose.yaml.j2"
    dest: "{{ docker_compose_rootdir }}/{{ docker_compose_projectname }}/docker-compose.yaml"
    mode: "0644"
    owner: "{{ docker_compose_files_owner }}"
    group: "{{ docker_compose_files_group }}"
- name: Get the version of docker compose
  check_mode: false
  environment:
    PATH: "{{ path_extension_list | join(':') }}:{{ lookup('env', 'PATH') }}"
  block:
    - name: Check the version of docker compose
      ansible.builtin.command:
        cmd: "docker compose version"
      register: docker_compose_version_output
      changed_when: false
    - name: Extract exact version
      ansible.builtin.set_fact:
        docker_compose_installed_version: "{{ docker_compose_version_output.stdout_lines[0]
          | regex_search('Docker Compose version v?([0-9\\.]*)', '\\1') | first }}"
    - name: Print out the docker compose version
      ansible.builtin.debug:
        var: docker_compose_installed_version
- name: Docker compose up
  become: "{{ docker_with_sudo }}"
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_rootdir }}/{{ docker_compose_projectname }}"
    docker_cli: "{{ docker_cli_path }}"
    remove_orphans: true
