- name: Deploy Nebula-sync as docker
  hosts: "{{ groups['dnsserver'][0] }}"
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: nebula-sync
    requested_image_version:
      nebula-sync: "ghcr.io/lovelaze/nebula-sync:v0.11.2"
