- name: Generate dynamic configuration for Glances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate configuration file from template
      ansible.builtin.template:
        src: config/templates/glances-values-private.yaml.j2
        dest: "glances-values-private.yaml"
