apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptimekuma-cert
spec:
  secretName: uptimekuma-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - uptimekuma.kubernetes.home
