- name: Deploy cadvisor as docker
  hosts: external
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: cadvisor
    requested_image_version:
      cadvisor: "ghcr.io/google/cadvisor:v0.60.3"
