apiVersion: v2
# renovate: image=ghcr.io/teelur/budget-board/server
appVersion: v3.0.0
dependencies:
  - name: common
    version: 29.5.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: budgetboard
type: application
version: 1.0.0
