- name: Deploy SOPS as a binary
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "getsops/sops:3.13.1"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: sops
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}-v{{ requested_binary_version }}.linux.amd64"
    compressed: false
    destination_path: "/usr/local/bin/{{ bin_filename }}"
