- name: Deploy age as a binary
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_version: "1.2.1"
    bin_filename: age
    binary_repository: "FiloSottile/age"
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}-v{{ requested_binary_version }}-linux-amd64.tar.gz"
