- name: Create nginx as docker
  hosts:
    - droplet
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: nginx
    requested_version:
      nginx: "1.28.0-perl"
    docker_compose_static_files_copy:
      - nginx-conf
