apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: networking-toolbox
  name: networking-toolbox-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: networking-toolbox
          port: 3000
  virtualhost:
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*"  # allows any origin
      allowMethods:
        - GET
        - POST
        - OPTIONS
      allowHeaders:
        - authorization
        - cache-control
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m"  # preflight requests can be cached for 10 minutes.
    fqdn: networking-toolbox.kubernetes.home
    tls:
      secretName: networking-toolbox-cert-secret
