- name: Copy all required scripts
  hosts: "*"
  roles:
    - scripts
- name: Install some packages
  hosts: "*"
  become: true
  roles:
    - package-install
  vars:
    packages:
      - sudo
      - vim
      - curl
- name: Set up vim
  hosts: "*"
  roles:
    - vim
- name: Set up NTP
  hosts: "*"
  become: true
  roles:
    - ntp
- name: Set up /etc/hosts
  hosts:
    - htpc
    - torrents22
  become: true
  roles:
    - hosts
  vars:
    hosts_dns_server: "@192.168.31.2"
    hosts_entries:
      - omv.home
      - synology216.home
- name: Set up /etc/fstab on htpc
  hosts:
    - htpc
  become: true
  roles:
    - fstab
  vars:
    fstab_entries:
      - src: synology216.home:/volume1/music/
        path: /mnt/Music/
      - src: omv.home:/export/Merged-Animation
        path: /mnt/Animation/
      - src: omv.home:/export/Merged-Anime
        path: /mnt/Anime/
      - src: omv.home:/export/Merged-Docu
        path: /mnt/Docu/
      - src: omv.home:/export/Merged-Movies
        path: /mnt/Movies/
      - src: omv.home:/export/Merged-AnimeSeries
        path: /mnt/AnimeSeries/
      - src: omv.home:/export/Merged-DocuSeries
        path: /mnt/DocuSeries/
      - src: omv.home:/export/Merged-TVSeries
        path: /mnt/TVSeries/
      - src: omv.home:/export/Shorts
        path: /mnt/Shorts/
- name: Set up /etc/fstab on torrents
  hosts:
    - torrents22
  become: true
  roles:
    - fstab
  vars:
    fstab_entries:
      - src: omv.home:/Movies-hdd01/
        path: /mnt/Movies-hdd01/
      - src: omv.home:/Movies-hdd02/
        path: /mnt/Movies-hdd02/
      - src: omv.home:/Movies-hdd03/
        path: /mnt/Movies-hdd03/
      - src: omv.home:/Movies-hdd04/
        path: /mnt/Movies-hdd04/
      - src: omv.home:/Movies-hdd05/
        path: /mnt/Movies-hdd05/
      - src: omv.home:/Movies-hdd06/
        path: /mnt/Movies-hdd06/
      - src: omv.home:/Movies-hdd07/
        path: /mnt/Movies-hdd07/
      - src: omv.home:/Anime-hdd01/
        path: /mnt/Anime-hdd01/
      - src: omv.home:/Anime-hdd02/
        path: /mnt/Anime-hdd02/
      - src: omv.home:/Anime-hdd03/
        path: /mnt/Anime-hdd03/
      - src: omv.home:/Anime-hdd04/
        path: /mnt/Anime-hdd04/
      - src: omv.home:/Anime-hdd05/
        path: /mnt/Anime-hdd05/
      - src: omv.home:/Anime-hdd06/
        path: /mnt/Anime-hdd06/
      - src: omv.home:/Anime-hdd07/
        path: /mnt/Anime-hdd07/
      - src: omv.home:/Docu-hdd01/
        path: /mnt/Docu-hdd01/
      - src: omv.home:/Docu-hdd02/
        path: /mnt/Docu-hdd02/
      - src: omv.home:/Docu-hdd03/
        path: /mnt/Docu-hdd03/
      - src: omv.home:/Docu-hdd04/
        path: /mnt/Docu-hdd04/
      - src: omv.home:/Docu-hdd05/
        path: /mnt/Docu-hdd05/
      - src: omv.home:/Docu-hdd06/
        path: /mnt/Docu-hdd06/
      - src: omv.home:/Docu-hdd07/
        path: /mnt/Docu-hdd07/
      - src: omv.home:/Animation-hdd01/
        path: /mnt/Animation-hdd01/
      - src: omv.home:/Animation-hdd02/
        path: /mnt/Animation-hdd02/
      - src: omv.home:/Animation-hdd03/
        path: /mnt/Animation-hdd03/
      - src: omv.home:/Animation-hdd04/
        path: /mnt/Animation-hdd04/
      - src: omv.home:/Animation-hdd05/
        path: /mnt/Animation-hdd05/
      - src: omv.home:/Animation-hdd06/
        path: /mnt/Animation-hdd06/
      - src: omv.home:/Animation-hdd07/
        path: /mnt/Animation-hdd07/
      - src: omv.home:/AnimeSeries-hdd01/
        path: /mnt/AnimeSeries-hdd01/
      - src: omv.home:/AnimeSeries-hdd02/
        path: /mnt/AnimeSeries-hdd02/
      - src: omv.home:/AnimeSeries-hdd03/
        path: /mnt/AnimeSeries-hdd03/
      - src: omv.home:/AnimeSeries-hdd04/
        path: /mnt/AnimeSeries-hdd04/
      - src: omv.home:/AnimeSeries-hdd05/
        path: /mnt/AnimeSeries-hdd05/
      - src: omv.home:/AnimeSeries-hdd06/
        path: /mnt/AnimeSeries-hdd06/
      - src: omv.home:/AnimeSeries-hdd07/
        path: /mnt/AnimeSeries-hdd07/
      - src: omv.home:/DocuSeries-hdd01/
        path: /mnt/DocuSeries-hdd01/
      - src: omv.home:/DocuSeries-hdd02/
        path: /mnt/DocuSeries-hdd02/
      - src: omv.home:/DocuSeries-hdd03/
        path: /mnt/DocuSeries-hdd03/
      - src: omv.home:/DocuSeries-hdd04/
        path: /mnt/DocuSeries-hdd04/
      - src: omv.home:/DocuSeries-hdd05/
        path: /mnt/DocuSeries-hdd05/
      - src: omv.home:/DocuSeries-hdd06/
        path: /mnt/DocuSeries-hdd06/
      - src: omv.home:/DocuSeries-hdd07/
        path: /mnt/DocuSeries-hdd07/
      - src: omv.home:/TVSeries-hdd01/
        path: /mnt/TVSeries-hdd01/
      - src: omv.home:/TVSeries-hdd02/
        path: /mnt/TVSeries-hdd02/
      - src: omv.home:/TVSeries-hdd03/
        path: /mnt/TVSeries-hdd03/
      - src: omv.home:/TVSeries-hdd04/
        path: /mnt/TVSeries-hdd04/
      - src: omv.home:/TVSeries-hdd05/
        path: /mnt/TVSeries-hdd05/
      - src: omv.home:/TVSeries-hdd06/
        path: /mnt/TVSeries-hdd06/
      - src: omv.home:/TVSeries-hdd07/
        path: /mnt/TVSeries-hdd07/
      - src: omv.home:/Shorts/
        path: /mnt/Shorts/
