# - name: Create smartctl_exporter as a service
#   hosts: proxmox
#   roles:
#     - create-service
#   vars:
#     requested_version: "0.14.0"
#     bin_filename: smartctl_exporter
#     service_name: smartctl-exporter
#     download_url: "https://github.com/prometheus-community/smartctl_exporter/releases/download/\
#           v{{ requested_version }}/{{ bin_filename }}-{{ requested_version }}.linux-amd64.tar.gz"
# - name: Create node_exporter as a service
#   hosts: proxmox
#   roles:
#     - create-service
#   vars:
#     requested_version: "1.9.1"
#     bin_filename: node_exporter
#     service_name: node-exporter
#     download_url: "https://github.com/prometheus/node_exporter/releases/download/\
#           v{{ requested_version }}/{{ bin_filename }}-{{ requested_version }}.linux-amd64.tar.gz"
# - name: Create smartctl_exporter as docker
#   hosts:
#     - htpc
#     - synology
#   roles:
#     - docker-compose
#   vars:
#     docker_compose_projectname: smartctl-exporter
#     requested_version: "0.14.0"
# - name: Create node_exporter as docker
#   hosts:
#     - standalone
#     - synology
#   roles:
#     - docker-compose
#   vars:
#     docker_compose_projectname: node-exporter
#     requested_version: "1.9.1"
# - name: Create portainer-agent as docker
#   hosts:
#     - standalone
#     - synology
#   roles:
#     - docker-compose
#   vars:
#     docker_compose_projectname: portainer-agent
#     requested_version: "2.30.0"
# - name: Create komodo-periphery as docker
#   hosts:
#     - standalone
#     - synology
#   roles:
#     - docker-compose
#   vars:
#     docker_compose_projectname: komodo-periphery
#     requested_version: "1.17.5"
#     docker_compose_create_dirs:
#       - config
- name: Create cup as docker
  hosts:
    - standalone
    - synology
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: cup
    requested_version: "3.4.0"
    docker_compose_create_dirs:
      - config
    docker_compose_template_configfiles_copy:
      - config/cup.json
    # cup_control_server: control
    # cup_servers:
    #   # control: http://192.168.31.164:8800
    #   torrents22: http://192.168.31.96:8800
    #   synology216: http://192.168.31.138:8800
    #   htpc: http://192.168.31.157:8800
    #   pihole: http://192.168.31.2:8800
    #   droplet: http://droplet.zkhome.dynu.net:8800
