---
- name: Copy Yamaha Receiver On/Off scripts
  copy:
    src: yamaha_start_stop.py
    dest: "{{ user_home }}/yamaha_start_stop.py"
    mode: 0755

- name: Copy Emby updater script
  copy:
    src: emby_updater.sh
    dest: "{{ user_home }}/emby_updater.sh"
    mode: 0755

- name: Copy ALSA info script script
  copy:
    src: alsa-info.sh
    dest: "{{ user_home }}/alsa-info.sh"
    mode: 0755

- name: Copy Music statistics script
  copy:
    src: music_stats.sh
    dest: "{{ user_home }}/music_stats.sh"
    mode: 0755

- name: Copy MPC Listen tool
  copy:
    src: mpdlisten.c
    dest: "{{ user_home }}/mpdlisten.c"
    mode: 0755
  register: sourcefile

- name: Compile MPD Listen tool
  shell: gcc mpdlisten.c -o mpdlisten -lmpdclient -std=c99
  when: sourcefile.changed

- name: Copy MPD Listen Autostart service
  become: yes
  template:
    src: mpdlisten.service.j2
    dest: "/etc/systemd/system/mpdlisten.service"
    mode: 0755
  register: servicefile

- name: Restart systemctl daemon
  become: true
  systemd:
    daemon_reload: yes
  when: servicefile.changed
