- name: Deploy Paperless-NGX as docker
  hosts: documents
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: paperless-ngx
    requested_image_version:
      paperless-ngx: "ghcr.io/paperless-ngx/paperless-ngx:2.20.15"
      valkey: "docker.io/valkey/valkey:9.1.1"
      postgres: "docker.io/library/postgres:18"
    docker_compose_create_dirs:
      - name: redisdata
      - name: pgdata
      - name: data
      # - name: media
      - name: export
      - name: consume
