- name: Create alloy as docker
  hosts:
    - standalone
    # - external
    # - synology
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: alloy
    requested_version:
      alloy: "1.9.2"
    docker_compose_create_dirs:
      - name: config
    docker_compose_template_files_copy:
      - name: config/config.alloy
