- name: Deploy alloy as service
  hosts: proxmox
  roles:
    - gpg-dearmor-repo
    - package-install
  vars:
    gpg_project_name: alloy
    gpg_key_url: https://packages.grafana.com/gpg.key
    gpg_signed_repo: "https://apt.grafana.com stable main"
    packages:
      - alloy
- name: Deploy alloy as docker
  hosts:
    - standalone
    # - external
    - synology
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: alloy
    requested_version:
      alloy: "1.9.2"
    docker_compose_create_dirs:
      - name: config
      - name: data
    docker_compose_template_files_copy:
      - name: config/config.alloy
