- name: Gather pip installed packages
  community.general.pip_package_info:
  register: pip_packages
  failed_when: false
- name: Handle pip packages
  when: pip_packages is defined
  block:
    - name: Upgrade pip packages
      ansible.builtin.pip:
        name: "{{ item.name }}"
        state: present
        version: "{{ item.version }}"
      loop: "{{ pip_packages_to_upgrade }}"
