apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: kuvasz
  name: kuvasz-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: kuvasz-kuvasz-uptime
          port: 8080
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    fqdn: kuvasz.kubernetes.home
    tls:
      secretName: kuvasz-cert-secret
