image:
  repository: ghcr.io/p2r3/convert
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    enabled: true
    ports:
      main:
        port: 80
        protocol: http
        targetPort: 80

persistence:
  nginx-cache:
    enabled: true
    type: emptyDir
    mountPath: /var/cache/nginx

TZ: Europe/Budapest

workload:
  main:
    enabled: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
