apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dockhand
  labels:
    app.kubernetes.io/name: dockhand
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dockhand
  namespaceSelector:
    matchNames:
      - dockhand
  endpoints:
    - port: main
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
