apiVersion: v2
# renovate: image=fnsys/dockhand
appVersion: v1.0.33
dependencies:
  - name: common
    version: 28.26.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: dockhand
type: application
version: 1.0.0
