apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: actualbudget
  name: actualbudget-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: actualbudget
          port: 5006
  virtualhost:
    fqdn: actualbudget.kubernetes.home
    tls:
      secretName: actualbudget-cert-secret
