apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wallos-cert
spec:
  secretName: wallos-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - wallos.kubernetes.home
