- name: Deploy node-exporter as docker
  hosts: docker
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: node-exporter
    requested_image_version:
      node-exporter: "quay.io/prometheus/node-exporter:v1.10.2"
