ansible-navigator:
  execution-environment:
    enabled: true
    image: ansible-execution-environment:latest
    pull:
      policy: never
  logging:
    level: debug
  playbook-artifact:
    enable: false
