ansible-navigator:
  execution-environment:
    enabled: true
    image: ansible-execution-environment:latest
    pull:
      policy: never
    volume-mounts:
      - src: /etc/hosts
        dest: /etc/hosts
        options: Z
      - src: $HOME/.ssh
        dest: /runner/.ssh
  logging:
    level: debug
  playbook-artifact:
    enable: false
