#!/usr/bin/env bash

# This script will check if there are updates, and send a push notification if true
# Requirements
#    - send_push.sh with proper setup
#    - On Ubuntu, place it in /etc/cron.daily

text="[[:digit:]]+ upgraded, [[:digit:]]+ newly installed, [[:digit:]]+ to remove and [[:digit:]]+ not upgraded"

message2=$(/usr/bin/apt-get -o Acquire::http::Dl-Limit=25 dist-upgrade -d -y -o APT::Get::Show-Upgraded=true | egrep "${text}")
res=$(echo ${message2} | tr -d -c [0-9])
if [ "${res}" != "0000" ]; then
  message1="Upgrades are pending on host $(hostname):"
  /home/qta/send_push.sh "${message1}
${message2}"
fi
