apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wazuh
resources:
  - ./wazuh-kubernetes/wazuh
patches:
  - patch: |-
      $patch: delete
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: wazuh-storage
  - target:
      kind: StatefulSet
      name: wazuh-manager-master
    patch: |-
      - op: remove
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-manager-master
        namespace: wazuh
      spec:
        volumeClaimTemplates:
          - metadata:
              name: wazuh-manager-master
              namespace: wazuh
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 30Gi
  - target:
      kind: StatefulSet
      name: wazuh-manager-worker
    patch: |-
      - op: remove
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-manager-worker
        namespace: wazuh
      spec:
        volumeClaimTemplates:
          - metadata:
              name: wazuh-manager-worker
              namespace: wazuh
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 30Gi
  - target:
      kind: StatefulSet
      name: wazuh-indexer
    patch: |-
      - op: remove
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: wazuh-indexer
        namespace: wazuh
      spec:
        template:
          spec:
            containers:
              - name: wazuh-indexer
                resources:
                  requests:
                    cpu: 500m
                    memory: 1Gi
                  limits:
                    cpu: 1
                    memory: 2Gi
        volumeClaimTemplates:
          - metadata:
              name: wazuh-indexer
              namespace: indexer-cluster
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
  - target:
      kind: Service
      name: dashboard
    patch: |-
      - op: add
        path: /metadata/annotations/metallb.io~1allow-shared-ip
        value: wazuh
  - target:
      kind: Service
      name: indexer
    patch: |-
      - op: add
        path: /metadata/annotations/metallb.io~1allow-shared-ip
        value: wazuh
  - target:
      kind: Service
      name: wazuh
    patch: |-
      - op: add
        path: /metadata/annotations/metallb.io~1allow-shared-ip
        value: wazuh
  - target:
      kind: Service
      name: wazuh-workers
    patch: |-
      - op: add
        path: /metadata/annotations/metallb.io~1allow-shared-ip
        value: wazuh
