- name: Create a new Service for the Intel NIC bug fix
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/disable-offloading.service
    mode: '0644'
    owner: root
    group: root
- name: Start the new service
  ansible.builtin.systemd_service:
    daemon_reexec: true
    daemon_reload: true
    name: disable-offloading
    state: started
    enabled: true
