apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: speedtest-cert
spec:
  secretName: speedtest-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - speedtest.kubernetes.home
