- name: Deploy nginx as docker
  hosts: external
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: nginx
    requested_image_version:
      nginx: "nginx:1.31.3-perl"
    docker_compose_static_files_copy:
      - name: nginx-conf
