---
- name: Copy SSH checker script on successful logins
  ansible.builtin.template:
    src: send_login.sh.j2
    dest: /usr/local/bin/send_login.sh
    mode: "0755"
- name: Copy SSH checker script on failed logins
  ansible.builtin.template:
    src: send_failed_login.sh.j2
    dest: /usr/local/bin/send_failed_login.sh
    mode: "0755"
