- name: Install some packages for mounting
  ansible.builtin.include_role:
    name: package-install
  vars:
    packages:
      - nfs-common
      - cifs-utils
- name: Make sure the directories exist (only if not mounted already)
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  when: ansible_mounts | selectattr('mount', 'equalto', item.path | dirname) | list | length == 0
  loop: "{{ fstab_entries }}"
- name: Unmount the given entries
  ansible.posix.mount:
    path: "{{ item.path }}"
    state: unmounted
  loop: "{{ fstab_entries }}"
- name: Mount the given entries
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: mounted
    fstype: "{{ item.fstype | default('nfs') }}"
    opts: "{{ item.opts | default('defaults,_netdev,x-systemd.requires=network-online.target,nofail,timeo=14') }}"
  loop: "{{ fstab_entries }}"
