apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wygiwyh-cert
spec:
  secretName: wygiwyh-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - wygiwyh.kubernetes.home
