postgresql:
  enabled: false

externalDatabase:
  host: kuvasz-postgresql
  port: 5432
  database: kuvasz
  user: kuvasz
  existingSecret: kuvasz-postgresql-db-password-secret
  existingSecretPasswordKey: password

extraVolumes:
  - name: ca-certificates
    secret:
      secretName: ca-certificates
extraVolumeMounts:
  - name: ca-certificates
    mountPath: /opt/java/openjdk/lib/security/cacerts
    subPath: cacerts

timezone: "Europe/Budapest"
