- name: Generate dynamic configuration for Cup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate configuration file from template
      ansible.builtin.template:
        src: config/templates/cup-values-config-private.yaml.j2
        dest: "cup-values-config-private.yaml"
