services:
  cup:
    container_name: cup
    command: -c /config/cup.json serve
    environment:
      - TZ=Europe/Budapest
    image: ghcr.io/sergi0g/cup:v3.4.3
    labels:
      kompose.volume.type: configMap
      kompose.service.group: cup
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./cup.json:/config/cup.json
