apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: stirling-pdf
  name: stirling-pdf-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: stirling-pdf-stirling-pdf-chart
          port: 8080
  virtualhost:
    fqdn: stirling-pdf.kubernetes.home
    tls:
      secretName: stirling-pdf-cert-secret
