apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stirling-pdf-cert
spec:
  secretName: stirling-pdf-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - stirling-pdf.kubernetes.home
