- name: Create netalertx as docker
  hosts:
    - pihole
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: netalertx
    requested_version:
      netalertx: "25.5.24"
    netalertx_interface: eth0
    netalertx_subnet: 192.168.31.0/24
