- name: Create portainer-agent as docker
  hosts:
    - standalone
    - synology
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: portainer-agent
    requested_version: "2.30.0"
