apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pve-vm-ct-down
spec:
  groups:
    - name: pve
      rules:
        - alert: PVEVM/CTDown
          expr: pve_up{id=~"(qemu|lxc)/.*"} == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: PVE host {{ $labels.host }} has VM/CT down
            description: "Proxmox VE guest {{ $labels.id }} is not running."
