apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: pulse
  name: pulse-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      permitInsecure: true
      services:
        - name: pulse
          port: 7655
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    fqdn: pulse.kubernetes.home
    tls:
      secretName: pulse-cert-secret
