apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: pulse
  name: pulse-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      permitInsecure: true
      services:
        - name: pulse
          port: 7655
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*" # allows any origin
      allowMethods:
        - GET
        - POST
        - OPTIONS
      allowHeaders:
        - authorization
        - cache-control
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m" # preflight requests can be cached for 10 minutes.
    fqdn: pulse.kubernetes.home
    tls:
      secretName: pulse-cert-secret
