apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pulse-cert
spec:
  secretName: pulse-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - pulse.kubernetes.home
