persistence:
  db:
    size: 1Gi
  media:
    size: 1Gi
workload:
  main:
    podSpec:
      containers:
        main:
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: "1"
              memory: 1Gi
