- name: Deploy smartctl-exporter as docker
  hosts: "{{ groups['smart'] | default([]) | intersect(groups['docker'] | default([])) }}"
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: smartctl-exporter
    requested_image_version:
      smartctl-exporter: "prometheuscommunity/smartctl-exporter:v0.14.0"
