- name: Delete smartctl
  hosts: "{{ groups['smart'] | default([]) | intersect(groups['docker'] | default([])) }}"
  roles:
    - docker-compose-remove
  vars:
    docker_compose_projectname: smartctl
