- name: Create cup as docker
  hosts:
    - standalone
    - synology
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: cup
    requested_version:
      cup: "3.4.0"
    docker_compose_create_dirs:
      - name: config
    docker_compose_template_files_copy:
      - name: config/cup.json
