apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: bentopdf
  name: bentopdf-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: bentopdf
          port: 8080
  virtualhost:
    fqdn: bentopdf.kubernetes.home
    tls:
      secretName: bentopdf-cert-secret
