apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bentopdf-cert
spec:
  secretName: bentopdf-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - bentopdf.kubernetes.home
