- name: Set up /etc/hosts
  hosts:
    - htpc
    - torrents22
  become: true
  roles:
    - hosts
  vars:
    hosts_dns_server: "@192.168.31.2"
    hosts_entries:
      - omv.home
      - synology216.home
