apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drydock-cert
spec:
  secretName: drydock-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - drydock.kubernetes.home
