apiVersion: v2
# renovate: image=lissy93/web-check
appVersion: 1.0.0
dependencies:
  - name: common
    version: 29.5.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: web-check
type: application
version: 1.0.0
