image:
  repository: louislam/uptime-kuma
  tag: 2.2.1
  pullPolicy: IfNotPresent
persistence:
  data:
    enabled: true
    accessModes: ReadWriteOnce
    mountPath: /app/data
    type: pvc
    size: 1Gi
securityContext:
  container:
    runAsGroup: 1000
    runAsUser: 1000
service:
  main:
    enabled: true
    ports:
      main:
        port: 3001
        protocol: http
        targetPort: 3001
TZ: Europe/Budapest
workload:
  main:
    enabled: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
