cluster:
  initdb:
    database: tianji
    owner: tianji
    secret:
      name: tianji-postgresql-db-password-secret
  instances: 1
  singleNode: true
  storage:
    size: 2Gi
  walStorage:
    size: 2Gi
  monitoring:
    enabled: true
    prometheusRule:
      enabled: false
