- name: Disable Ubuntu default Stub DNS Resolver
  ansible.builtin.lineinfile:
    path: "/etc/systemd/resolved.conf"
    state: present
    line: 'DNSStubListener=no'
    regexp: '#?\s*DNSStubListener=.*'
- name: Relink resolve.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    force: true
    state: link
    src: /run/systemd/resolve/resolv.conf
- name: Copy docker compose file
  ansible.builtin.template:
    src: docker_compose.yaml.j2
    dest: "{{ docker_compose_rootdir }}/{{ pihole_docker_compose_projectdir }}/docker-compose.yaml"
    mode: "0664"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
- name: Docker compose up
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_rootdir }}/{{ pihole_docker_compose_projectdir }}"
