apiVersion: v2
# renovate: image=codeswhat/drydock
appVersion: 1.3.9
dependencies:
  - name: common
    version: 29.5.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: drydock
type: application
version: 1.0.0
