- name: Turn off systemd-resolved
  become: true
  hosts: pihole
  tasks:
    - name: Disable Ubuntu default Stub DNS Resolver
      ansible.builtin.lineinfile:
        path: "/etc/systemd/resolved.conf"
        state: present
        line: 'DNSStubListener=no'
        regexp: '#?\s*DNSStubListener=.*'
    - name: Relink resolve.conf
      ansible.builtin.file:
        path: /etc/resolv.conf
        force: true
        state: link
        src: /run/systemd/resolve/resolv.conf
- name: Create pihole as docker
  hosts: pihole
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: pihole
    requested_version:
      pihole: "2025.04.0"
      unbound: "1.22.0"
