- name: Create nginx as docker
  hosts:
    - droplet
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: nginx
    requested_version: "1.28.0-perl"
    docker_compose_static_configfiles_copy:
      - nginx-conf
- name: Create rustdesk as docker
  hosts:
    - droplet
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: rustdesk
    requested_version: "1.1.14"
