- name: Create inadyn as docker
  hosts:
    - control
    - torrents22
    - htpc
    - synology
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: inadyn
    requested_version: "2.12.0"
    docker_compose_template_configfiles_copy:
      - config/inadyn.conf
- name: Create ddclient as docker
  hosts:
    - droplet
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: ddclient
    requested_version: "4.0.0"
    docker_compose_template_configfiles_copy:
      - config/ddclient.conf
