- name: Setup pihole
  hosts: pihole
  become: true
  roles:
    - docker-compose-pihole
  vars:
    pihole_requested_version: "2025.04.0"
    pihole_unbound_requested_version: "1.22.0"
    pihole_ip_address: "192.168.31.2"
    pihole_password: "piholeS3rv3r"
