- name: Deploy nginx proxy
  ansible.builtin.import_playbook: selfhosting/nginx-proxy/deploy-nginx-proxy.yaml
- name: Deploy rustdesk
  ansible.builtin.import_playbook: selfhosting/rustdesk/deploy-rustdesk.yaml
- name: Deploy kr-docu-decrypt
  ansible.builtin.import_playbook: selfhosting/kr-docu-decrypt/deploy-kr-docu-decrypt.yaml
