- name: Deploy Tugtainer as docker
  hosts: docker
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: tugtainer
    requested_image_version:
      tugtainer: "quenary/tugtainer:v1.30.8"
    docker_compose_create_dirs:
      - name: data
