- name: Print the package manager
  ansible.builtin.debug:
    msg: System {{ inventory_hostname }} has package manager {{ ansible_pkg_mgr }}
- name: Update the system packages
  when: ansible_pkg_mgr == 'apt'
  block:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
    - name: Upgrade APT packages
      ansible.builtin.apt:
        upgrade: dist
    - name: Remove obsolete APT packages
      ansible.builtin.apt:
        autoremove: true
    - name: Clean APT cache
      ansible.builtin.apt:
        autoclean: true
    - name: Check reboot status
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot
      changed_when: reboot.stat.exists
      # notify: Perform reboot
