apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: uptimekuma
  name: uptimekuma-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: uptimekuma
          port: 3001
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    fqdn: uptimekuma.kubernetes.home
    tls:
      secretName: uptimekuma-cert-secret
