- name: Install some python-related packages
  hosts: controlserver
  become: true
  roles:
    - package-install
  vars:
    packages:
      - python3-pip
      - python3.12-venv
      - pipx
- name: Install some pip packages
  hosts: controlserver
  become: true
  roles:
    - package-update-pipx
  vars:
    pipx_packages:
      - ansible-dev-tools
