- name: Install some generic packages everywhere
  hosts: "*"
  become: true
  roles:
    - package-install
  vars:
    packages:
      - curl
      - gpg
      - jq
      - sudo
      - ufw
      - vim
