- name: Install some generic packages everywhere
  hosts: "*"
  become: true
  roles:
    - package-install
  vars:
    packages:
      - curl
      - gpg
      - jq
      - python3-pip
      - sudo
      - ufw
      - vim
- name: Deploy yq
  hosts: control
  roles:
    - binary-install
  vars:
    requested_version: "4.47.2"
    bin_filename: yq
    download_url: "https://github.com/mikefarah/{{ bin_filename }}/releases/download/\
          v{{ requested_version }}/{{ bin_filename }}_linux_amd64"
    compressed: false
    destination_path: /usr/local/bin/yq
