- name: Install some generic packages
  hosts: linux-selfmanaged
  become: true
  roles:
    - package-install
  vars:
    packages:
      - bash-completion
      - curl
      - dnsutils
      - gpg
      - jq
      - logrotate
      - needrestart
      - sudo
      - ufw
- name: Deploy yq
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "mikefarah/yq:4.47.2"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: yq
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}_linux_amd64"
    compressed: false
    destination_path: "/usr/local/bin/{{ bin_filename }}"
