- name: Install some generic packages everywhere
  hosts: linux
  become: true
  roles:
    - package-install
  vars:
    packages:
      - bash-completion
      - curl
      - dnsutils
      - gpg
      - jq
      - sudo
      - ufw
      - vim
- name: Deploy yq
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_version: "4.47.2"
    bin_filename: yq
    download_url: "https://github.com/mikefarah/{{ bin_filename }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}_linux_amd64"
    compressed: false
    destination_path: /usr/local/bin/yq
