- name: Install terraform
  hosts: controlserver
  become: true
  roles:
    - package-install
  vars:
    gpg_dearmor: true
    gpg_project_name: hashicorp-archive-keyring
    gpg_key_url: https://apt.releases.hashicorp.com/gpg
    gpg_signed_repo: "https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
    packages:
      - terraform
