- name: Deploy <APP_NAME> as binary
  hosts: <ANSIBLE_HOST>
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "<REPO_AND_VERSION>"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: <APP_NAME_LOWERCASE>
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}_{{ requested_binary_version }}_Linux_x86_64.tar.gz"
    version_flag: "version"
