alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi

grafana:
  deploymentStrategy:
    type: Recreate
  persistence:
    enabled: true
    size: 20Gi
  additionalDataSources:
    - name: Loki
      access: proxy
      isDefault: false
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: Home
      orgId: 1
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local/

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi

prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: host
          action: replace
