alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi

grafana:
  persistence:
    enabled: true
    size: 20Gi
  additionalDataSources:
    - name: Loki
      access: proxy
      isDefault: false
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: Home
      orgId: 1
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local/

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
