apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana-httpproxy
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: kube-prometheus-stack-grafana
      port: 80
  virtualhost:
    fqdn: grafana.kubernetes.home
    tls:
      secretName: grafana-cert-secret
