services:
  smokeping:
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      #- MASTER_URL=http://<master-host-ip>:80/smokeping/
      #- SHARED_SECRET=password
      #- CACHE_DIR=/tmp
    hostname: smokeping
    image: lscr.io/linuxserver/smokeping:2.9.0
    labels:
      kompose.volume.type: persistentVolumeClaim
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./data:/data
