image:
  repository: ghcr.io/transmute-app/transmute
  tag: v1.0.0
  pullPolicy: IfNotPresent
persistence:
  data:
    enabled: true
    accessModes: ReadWriteOnce
    mountPath: /app/data
    type: pvc
service:
  main:
    enabled: true
    ports:
      main:
        port: 3313
        protocol: http
        targetPort: 3313
TZ: Europe/Budapest
workload:
  main:
    enabled: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
