apiVersion: v2
# renovate: image=ghcr.io/pdfcrafttool/pdfcraft
appVersion: 2025.10.12
dependencies:
  - name: common
    version: 29.5.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: pdfcraft
type: application
version: v2026.03.25
