apiVersion: v2
appVersion: 2025.10.12
dependencies:
  - name: common
    version: 28.26.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: pdfcraft
type: application
version: v2026.03.25
