- name: Deploy nut-exporter as docker
  hosts: nutserver
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: nut-exporter
    requested_image_version:
      nut-exporter: "druggeri/nut_exporter:3.3.0"
