- name: Deploy smartctl-exporter as a service
  hosts: "{{ groups['smart'] | difference(groups['docker']) }}"
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "prometheus-community/smartctl_exporter:0.14.0"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: smartctl_exporter
    service_name: smartctl-exporter
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}-{{ requested_binary_version }}.linux-amd64.tar.gz"
- name: Deploy smartctl-exporter as docker
  hosts: "{{ groups['smart'] | intersect(groups['docker']) }}"
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: smartctl-exporter
    requested_image_version:
      smartctl-exporter: "prometheuscommunity/smartctl-exporter:v0.14.0"
