- name: Deploy kubeconform
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "yannh/kubeconform:0.7.0"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: kubeconform
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}-linux-amd64.tar.gz"
    version_flag: "-v"
    decompression_options:
      - "--wildcards"
      - "{{ bin_filename }}"
