- name: Deploy kubens
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "ahmetb/kubectx:0.11.0"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: kubens
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}_v{{ requested_binary_version }}_linux_x86_64.tar.gz"
    decompression_options:
      - "--wildcards"
      - "{{ bin_filename }}*"
