- name: Deploy krew
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "kubernetes-sigs/krew:0.4.5"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: kubectl-krew
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/krew-linux_amd64.tar.gz"
    bin_path: "{{ ansible_user_dir }}/.krew/bin"
    install_cmd: "./krew-linux_amd64 install krew"
    version_flag: "version"
- name: Deploy krew plugins
  hosts: controlserver
  tasks:
    - name: Ensure krew plugins are installed
      ansible.builtin.command:
        cmd: "kubectl krew install {{ item }}"
      changed_when: true
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.krew/bin"
      loop:
        - access-matrix
        - ai
        - aperf
        - cnpg
        - cond
        - deprecations
        - df-pv
        - doctor
        - exec-as
        - flame
        - gadget
        - grep
        - ice
        - images
        - klock
        - kor
        - ktop
        - kubetail
        - kurt
        - neat
        - node-resource
        - ns
        - popeye
        - preq
        - pvu
        - rbac-tool
        - resource-capacity
        - rolesum
        - rook-ceph
        - score
        - starboard
        - status
        - stern
        - tail
        - trace
        - tree
        - view-allocations
        - view-cert
        - view-quotas
        - view-secret
        - whoami
        - whoami-enhanced
        - who-can
        - why-pending
