{
 "title": "Homelab Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall CPU Utilization (Hottest core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (host) (\r\n    rate(\r\n        node_cpu_seconds_total{\r\n            mode!=\"idle\",\r\n            job=\"node-exporter\"\r\n        }[$__rate_interval]\r\n    )\r\n)",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "max by (host) (\r\n    rate(\r\n        windows_cpu_time_total{\r\n            mode!=\"idle\",\r\n            job=\"windows-exporter\"\r\n        }[$__rate_interval]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures (Max)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (host) (node_hwmon_temp_celsius)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"control-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "htpc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"htpc-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "piHole",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"pihole-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "omv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"omv-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Synology216",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"synology216-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Synology224",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"synology224-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "qotom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"qotom-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"cadvisor\",\r\n            host=\"vps\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Worker1 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{node=\"k8s-worker-1\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_node_status_capacity{job=\"kube-state-metrics\", node=\"k8s-worker-1\", resource=\"cpu\"}\r\n)",
     "legendFormat": "Max Capacity"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{node=\"k8s-worker-1\"}\r\n)",
     "legendFormat": "Sum of Requests"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{node=\"k8s-worker-1\"}\r\n)",
     "legendFormat": "Sum of Limits"
    }
   ]
  },
  {
   "title": "Worker2 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{node=\"k8s-worker-2\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_node_status_capacity{job=\"kube-state-metrics\", node=\"k8s-worker-2\", resource=\"cpu\"}\r\n)",
     "legendFormat": "Max Capacity"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{node=\"k8s-worker-2\"}\r\n)",
     "legendFormat": "Sum of Requests"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{node=\"k8s-worker-2\"}\r\n)",
     "legendFormat": "Sum of Limits"
    }
   ]
  },
  {
   "title": "Worker3 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{node=\"k8s-worker-3\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_node_status_capacity{job=\"kube-state-metrics\", node=\"k8s-worker-3\", resource=\"cpu\"}\r\n)",
     "legendFormat": "Max Capacity"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{node=\"k8s-worker-3\"}\r\n)",
     "legendFormat": "Sum of Requests"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{node=\"k8s-worker-3\"}\r\n)",
     "legendFormat": "Sum of Limits"
    }
   ]
  },
  {
   "title": "Worker1 Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  node_namespace_pod_container:container_memory_working_set_bytes{node=\"k8s-worker-1\", container!=\"\", service=\"prometheus-kubelet\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_node_status_capacity{job=\"kube-state-metrics\", node=\"k8s-worker-1\", resource=\"memory\"}\r\n)",
     "legendFormat": "Max Capacity"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{node=\"k8s-worker-1\"}\r\n)",
     "legendFormat": "Sum of Requests"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{node=\"k8s-worker-1\"}\r\n)",
     "legendFormat": "Sum of Limits"
    }
   ]
  },
  {
   "title": "Worker2 Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  node_namespace_pod_container:container_memory_working_set_bytes{node=\"k8s-worker-2\", container!=\"\", service=\"prometheus-kubelet\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_node_status_capacity{job=\"kube-state-metrics\", node=\"k8s-worker-2\", resource=\"memory\"}\r\n)",
     "legendFormat": "Max Capacity"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{node=\"k8s-worker-2\"}\r\n)",
     "legendFormat": "Sum of Requests"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{node=\"k8s-worker-2\"}\r\n)",
     "legendFormat": "Sum of Limits"
    }
   ]
  },
  {
   "title": "Worker3 Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  node_namespace_pod_container:container_memory_working_set_bytes{node=\"k8s-worker-3\", container!=\"\", service=\"prometheus-kubelet\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_node_status_capacity{job=\"kube-state-metrics\", node=\"k8s-worker-3\", resource=\"memory\"}\r\n)",
     "legendFormat": "Max Capacity"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{node=\"k8s-worker-3\"}\r\n)",
     "legendFormat": "Sum of Requests"
    },
    {
     "expr": "sum(\r\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{node=\"k8s-worker-3\"}\r\n)",
     "legendFormat": "Sum of Limits"
    }
   ]
  },
  { "title": "S.M.A.R.T.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "S.M.A.R.T. HDD Error count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (smartctl_device_attribute{\r\n    attribute_value_type=\"raw\",\r\n    host=~\"(proxmox-nas|synology.*)\",\r\n    attribute_name!~\"^(Temperature_Celsius|Spin_Up_Time|Load_Cycle_Count|Power_On_Hours|Power-Off_Retract_Count|Power_Cycle_Count|Throughput_Performance|Seek_Time_Performance|Helium_Level|Start_Stop_Count)$\"\r\n}) by (host, device)",
     "legendFormat": "{{host}}/{{device}} - {{attribute_name}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T. SSD %left",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_attribute{\r\n    attribute_name=\"Wear_Leveling_Count\",\r\n    attribute_value_type=\"value\"\r\n}",
     "legendFormat": "{{host}}/{{device}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T. NVME %left",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - smartctl_device_percentage_used{}",
     "legendFormat": "{{host}}/{{device}}"
    },
    {
     "expr": "smartctl_device_attribute{\r\n    attribute_value_type=\"raw\",\r\n    attribute_name=\"SSD_Life_Left\"\r\n}",
     "legendFormat": "{{host}}/{{device}}"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Disk space occupancy% for other systems",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_join (\r\n    label_replace(\r\n        100 * (\r\n            node_filesystem_size_bytes{\r\n                job=\"node-exporter\",\r\n                host!~\"^(k8s.*|proxmox[1-9].*)$\",\r\n                fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n                mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n            } - node_filesystem_avail_bytes{\r\n                job=\"node-exporter\",\r\n                host!~\"^(k8s.*|proxmox[1-9].*)$\",\r\n                fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n                mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n            }\r\n        ) / node_filesystem_size_bytes{\r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s.*|proxmox[1-9].*)$\",\r\n            fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n            mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n        },\r\n         \"mountpoint\",\r\n        \"disk-${1}\",\r\n        \"mountpoint\",\r\n        \".*/dev-disk-by-uuid-([a-f0-9]+).*\"\r\n    ),\r\n\"host_and_mount\", \"@\", \"host\", \"mountpoint\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join (\r\n    100 * (windows_logical_disk_size_bytes{\r\n        volume=\"C:\"\r\n    } - windows_logical_disk_free_bytes{\r\n        volume=\"C:\"\r\n    }) / windows_logical_disk_size_bytes{\r\n        volume=\"C:\"\r\n    },\r\n\"host_and_mount\", \"@\", \"host\", \"mountpoint\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space occupancy% for K8s PVCs",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  max by (persistentvolumeclaim, namespace) (\r\n    kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}\r\n  )\r\n  -\r\n  max by (persistentvolumeclaim, namespace) (\r\n    kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}\r\n  )\r\n)\r\n/\r\nmax by (persistentvolumeclaim, namespace) (\r\n  kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\"}\r\n)\r\n* 100",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk space occupancy% for K8s",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_join (\r\n    100 * (\r\n        node_filesystem_size_bytes{\r\n            job=\"node-exporter\",\r\n            host=~\"^(k8s.*|proxmox.*)$\",\r\n            fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n            mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n        } - node_filesystem_avail_bytes{\r\n            job=\"node-exporter\",\r\n            host=~\"^(k8s.*|proxmox.*)$\",\r\n            fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n            mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n        }\r\n    ) / node_filesystem_size_bytes{\r\n        job=\"node-exporter\",\r\n        host=~\"^(k8s.*|proxmox.*)$\",\r\n        fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n        mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n    },\r\n    \"host_and_mount\", \"@\", \"host\", \"mountpoint\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n  ceph_cluster_total_used_bytes / ceph_cluster_total_bytes * 100,\r\n  \"host_and_mount\", \"Rook-Ceph\", \"\", \"\"\r\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        node_network_receive_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\",\r\n            job=\"node-exporter\", \r\n            host!~\"^(proxmox.*|k8s-.*|)$\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (host)",
     "legendFormat": "{{host}} - Rx in"
    },
    {
     "expr": "sum (\r\n    rate(\r\n        node_network_transmit_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\", \r\n            host!~\"^(proxmox.*|k8s-.*|)$\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (host)",
     "legendFormat": "{{host}} - Tx out"
    },
    {
     "expr": "sum (\r\n    rate(\r\n        windows_net_bytes_received_total{\r\n            job=\"windows-exporter\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (host)",
     "legendFormat": "{{host}} - Rx in"
    },
    {
     "expr": "sum (\r\n    rate(\r\n        windows_net_bytes_sent_total{\r\n            job=\"windows-exporter\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (host)",
     "legendFormat": "{{host}} - Tx out"
    }
   ]
  },
  {
   "title": "control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"control\",\r\n            job=\"control-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"control\",\r\n            job=\"control-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "htpc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"htpc\",\r\n            job=\"htpc-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"htpc\",\r\n            job=\"htpc-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "pihole",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"pihole\",\r\n            job=\"pihole-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"pihole\",\r\n            job=\"pihole-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "omv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"omv\",\r\n            job=\"omv-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"omv\",\r\n            job=\"omv-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "synology216",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"synology216\",\r\n            job=\"synology216-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"synology216\",\r\n            job=\"synology216-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "synology224",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"synology224\",\r\n            job=\"synology224-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"synology224\",\r\n            job=\"synology224-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "Qotom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"qotom\",\r\n            job=\"qotom-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"qotom\",\r\n            job=\"qotom-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 84 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "K8s system networking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            job=~\"kubelet\",\r\n            namespace=~\"^(kube-system|metallb-system|rook-ceph|projectcontour|cnpg-system|monitoring|default)$\"\r\n        }[$__rate_interval]\r\n    ) * on (namespace,pod) group_left ()\r\n    topk by (namespace,pod) (\r\n      1,\r\n      max by (namespace,pod) (kube_pod_info{host_network=~\"(true|false)\"})\r\n    )\r\n)",
     "legendFormat": "{{namespace}} - Rx in"
    },
    {
     "expr": "sum by (namespace) (\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            job=~\"kubelet\",\r\n            namespace=~\"^(kube-system|metallb-system|rook-ceph|projectcontour|cnpg-system|monitoring|default)$\"\r\n        }[$__rate_interval]\r\n    ) * on (namespace,pod) group_left ()\r\n    topk by (namespace,pod) (\r\n      1,\r\n      max by (namespace,pod) (kube_pod_info{host_network=~\"(true|false)\"})\r\n    )\r\n)",
     "legendFormat": "{{namespace}} - Tx out"
    }
   ]
  },
  {
   "title": "K8s app networking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            job=~\"kubelet\",\r\n            namespace!~\"^(kube-system|metallb-system|rook-ceph|projectcontour|cnpg-system|monitoring|default)$\"\r\n        }[$__rate_interval]\r\n    ) * on (namespace,pod) group_left ()\r\n    topk by (namespace,pod) (\r\n      1,\r\n      max by (namespace,pod) (kube_pod_info{host_network=~\"(true|false)\"})\r\n    )\r\n)",
     "legendFormat": "{{namespace}} - Rx in"
    },
    {
     "expr": "sum by (namespace) (\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            job=~\"kubelet\",\r\n            namespace!~\"^(kube-system|metallb-system|rook-ceph|projectcontour|cnpg-system|monitoring|default)$\"\r\n        }[$__rate_interval]\r\n    ) * on (namespace,pod) group_left ()\r\n    topk by (namespace,pod) (\r\n      1,\r\n      max by (namespace,pod) (kube_pod_info{host_network=~\"(true|false)\"})\r\n    )\r\n)",
     "legendFormat": "{{namespace}} - Tx out"
    }
   ]
  },
  {
   "title": "Traffic Tx - Yesterday",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_transmit_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s-.*|)$\"\r\n        }[24h]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_sent_total{\r\n            job=\"windows-exporter\"\r\n        }[24h]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Tx - Today",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_transmit_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\", \r\n            host!~\"^(k8s-.*|)$\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_sent_total{\r\n            job=\"windows-exporter\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Tx - Last hour",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_transmit_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s-.*|)$\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_sent_total{\r\n            job=\"windows-exporter\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rx - Yesterday",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_receive_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s-.*|)$\"\r\n        }[24h]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_received_total{\r\n            job=\"windows-exporter\"\r\n        }[24h]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rx - Today",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_receive_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\", \r\n            host!~\"^(k8s-.*|)$\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_received_total{\r\n            job=\"windows-exporter\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rx - Last hour",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_receive_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s-.*|)$\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_received_total{\r\n            job=\"windows-exporter\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}