- name: Deploy LibreSpeed as docker
  hosts: networkmonitoring
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: librespeed
    requested_image_version:
      librespeed: "ghcr.io/librespeed/speedtest:5.4.1"
