- name: Deploy cup as docker
  hosts: docker
  roles:
    - docker-compose
  vars_files:
    - defaults.yaml
  vars:
    docker_compose_projectname: cup
    requested_image_version:
      cup: "3.4.3"
    docker_compose_create_dirs:
      - name: config
    docker_compose_template_files_copy:
      - name: config/cup.json
