- name: Deploy alloy as service
  hosts: proxmox
  roles:
    - package-install
  vars:
    gpg_dearmor: true
    gpg_project_name: alloy
    gpg_key_url: https://packages.grafana.com/gpg.key
    gpg_signed_repo: "https://apt.grafana.com stable main"
    packages:
      - alloy
