---
- name: Copy torrent notification script
  template:
    src: push_torrent.sh.j2
    dest: "{{ user_home }}/push_torrents.sh"
    mode: 0755

- name: Edit .rtorrent.rc file
  lineinfile:
    path: "{{ user_home }}/.rtorrent.rc"
    regexp: '.*push_torrent.sh.*'
    line: 'system.method.set_key = event.download.finished,notify_me,"execute=~/push_torrent.sh,$d.name="'
    insertafter: EOF
  register: rtorrentrcfile

- name: Restart systemctl daemon
  block:
    - name: Stop rtorrent
      shell: '/bin/bash -i -c "stop-rtorrent && start-rtorrent"'
      ignore_errors: true
      args:
        executable: /bin/bash
  when: rtorrentrcfile.changed
