apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: searxng-cert
spec:
  secretName: searxng-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - searxng.kubernetes.home
