apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: databasus
  name: databasus-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: databasus-service
          port: 4005
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*" # allows any origin
      allowMethods:
        - GET
        - POST
        - OPTIONS
      allowHeaders:
        - authorization
        - cache-control
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m" # preflight requests can be cached for 10 minutes.
    fqdn: databasus.kubernetes.home
    tls:
      secretName: databasus-cert-secret
