- name: Install pip
  ansible.builtin.command:
    cmd: python3 -m ensurepip --upgrade
  changed_when: true
- name: Install prerequisites in pip
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - requests==2.31.0
    - docker==6.1.3
    - docker-compose
- name: Download docker compose v2
  block:
    - name: Create docker plugin directory
      ansible.builtin.file:
        path: "{{ synology_docker_cliplugin_path }}"
        state: directory
        mode: "0755"
        owner: root
        group: root
    - name: Download the requested version of compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ synology_docker_compose_v2_version }}/docker-compose-linux-x86_64"
        dest: "{{ synology_docker_cliplugin_path }}/docker-compose"
        mode: "0755"
