{
 "title": "Homelab Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall CPU Utilization (Hottest core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (host) (\r\n    rate(\r\n        node_cpu_seconds_total{\r\n            mode!=\"idle\",\r\n            job=\"node-exporter\"\r\n        }[$__rate_interval]\r\n    )\r\n)",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "max by (host) (\r\n    rate(\r\n        windows_cpu_time_total{\r\n            mode!=\"idle\",\r\n            job=\"windows-exporter\"\r\n        }[$__rate_interval]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures (Max)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (host) (node_hwmon_temp_celsius)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"control-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "htpc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"htpc-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "piHole",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"pihole-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "torrents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"torrents-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Synology216",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"synology216-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            job=\"vps-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    )\r\n) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "S.M.A.R.T.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "S.M.A.R.T. HDD Error count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (smartctl_device_attribute{\r\n    attribute_value_type=\"raw\",\r\n    host=~\"(omv|synology.*)\",\r\n    attribute_name!~\"^(Temperature_Celsius|Spin_Up_Time|Load_Cycle_Count|Power_On_Hours|Power-Off_Retract_Count|Power_Cycle_Count|Throughput_Performance|Seek_Time_Performance|Helium_Level|Start_Stop_Count)$\"\r\n}) by (host, device)",
     "legendFormat": "{{host}}/{{device}} - {{attribute_name}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T. SSD %left",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_attribute{\r\n    attribute_name=\"Wear_Leveling_Count\",\r\n    attribute_value_type=\"value\"\r\n}",
     "legendFormat": "{{host}}/{{device}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T. NVME %left",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-smartctl_device_percentage_used{}",
     "legendFormat": "{{host}}/{{device}}"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk space occupancy% for K8s",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_join (\r\n    100 * (\r\n        node_filesystem_size_bytes{\r\n            job=\"node-exporter\",\r\n            host=~\"^(k8s.*|proxmox.*)$\",\r\n            fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n            mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n        } - node_filesystem_avail_bytes{\r\n            job=\"node-exporter\",\r\n            host=~\"^(k8s.*|proxmox.*)$\",\r\n            fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n            mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n        }\r\n    ) / node_filesystem_size_bytes{\r\n        job=\"node-exporter\",\r\n        host=~\"^(k8s.*|proxmox.*)$\",\r\n        fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n        mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n    },\r\n    \"host_and_mount\", \"@\", \"host\", \"mountpoint\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk space occupancy% for other systems",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_join (\r\n    100 * (\r\n        node_filesystem_size_bytes{\r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s.*|proxmox.*)$\",\r\n            fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n            mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n        } - node_filesystem_avail_bytes{\r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s.*|proxmox.*)$\",\r\n            fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n            mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n        }\r\n    ) / node_filesystem_size_bytes{\r\n        job=\"node-exporter\",\r\n        host!~\"^(k8s.*|proxmox.*)$\",\r\n        fstype!~\"^(nfs|tmpfs|vfat|fuse).*$\",\r\n        mountpoint=~\"^(/|/volume1|/srv/.*)$\"\r\n    },\r\n\"host_and_mount\", \"@\", \"host\", \"mountpoint\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join (\r\n    100 * (windows_logical_disk_size_bytes{\r\n        volume=\"C:\"\r\n    } - windows_logical_disk_free_bytes{\r\n        volume=\"C:\"\r\n    }) / windows_logical_disk_size_bytes{\r\n        volume=\"C:\"\r\n    },\r\n\"host_and_mount\", \"@\", \"host\", \"mountpoint\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum (\r\n    rate(\r\n        node_network_receive_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\",\r\n            job=\"node-exporter\", \r\n            host!~\"^(proxmox.*|k8s-.*|)$\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (host)",
     "legendFormat": "{{host}} - Rx in"
    },
    {
     "expr": "sum (\r\n    rate(\r\n        node_network_transmit_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\", \r\n            host!~\"^(proxmox.*|k8s-.*|)$\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (host)",
     "legendFormat": "{{host}} - Tx out"
    },
    {
     "expr": "sum (\r\n    rate(\r\n        windows_net_bytes_received_total{\r\n            job=\"windows-exporter\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (host)",
     "legendFormat": "{{host}} - Rx in"
    },
    {
     "expr": "sum (\r\n    rate(\r\n        windows_net_bytes_sent_total{\r\n            job=\"windows-exporter\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (host)",
     "legendFormat": "{{host}} - Tx out"
    }
   ]
  },
  {
   "title": "control",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"control\",\r\n            job=\"control-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"control\",\r\n            job=\"control-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "htpc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"htpc\",\r\n            job=\"htpc-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"htpc\",\r\n            job=\"htpc-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "pihole",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"pihole\",\r\n            job=\"pihole-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"pihole\",\r\n            job=\"pihole-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "torrents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"torrents\",\r\n            job=\"torrents-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"torrents\",\r\n            job=\"torrents-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "synology216",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_receive_bytes_total{\r\n            host=\"synology216\",\r\n            job=\"synology216-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Rx in"
    },
    {
     "expr": "sum(\r\n    rate(\r\n        container_network_transmit_bytes_total{\r\n            host=\"synology216\",\r\n            job=\"synology216-metrics\",\r\n            name=~\".+\"\r\n        }[$__rate_interval]\r\n    ) * 8\r\n) by (name)",
     "legendFormat": "{{name}} - Tx out"
    }
   ]
  },
  {
   "title": "Traffic Rx - Today",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_receive_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\", \r\n            host!~\"^(k8s-.*|)$\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_received_total{\r\n            job=\"windows-exporter\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Tx - Today",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_transmit_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\", \r\n            host!~\"^(k8s-.*|)$\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_sent_total{\r\n            job=\"windows-exporter\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rx - Last hour",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_receive_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s-.*|)$\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_received_total{\r\n            job=\"windows-exporter\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Tx - Last hour",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_transmit_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s-.*|)$\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_sent_total{\r\n            job=\"windows-exporter\"\r\n        }[$__range]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rx - Yesterday",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_receive_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s-.*|)$\"\r\n        }[24h]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_received_total{\r\n            job=\"windows-exporter\"\r\n        }[24h]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Tx - Yesterday",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        node_network_transmit_bytes_total{\r\n            device!~\"^(veth.*|lo|nodelocaldns|tap.*|vxlan.*|docker.*|kube.*|cali.*|br-.*)$\", \r\n            job=\"node-exporter\",\r\n            host!~\"^(k8s-.*|)$\"\r\n        }[24h]\r\n    )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(host) (\r\n    increase(\r\n        windows_net_bytes_sent_total{\r\n            job=\"windows-exporter\"\r\n        }[24h]\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}