apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smokeping-cert
spec:
  secretName: smokeping-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - smokeping.kubernetes.home
