docker_compose_create_dirs: []
docker_compose_extra_volumes: []
docker_compose_files_owner: "{{ lookup('env', 'USER') }}"
docker_compose_files_group: "{{ lookup('env', 'USER') }}"
docker_compose_ipv6: false
docker_compose_projectname: "{{ undef(hint='You must specify the docker compose project name') }}"
docker_compose_rootdir: "{{ ansible_user_dir }}/docker-compose"
docker_compose_static_configfiles_copy: []
docker_compose_template_configfiles_copy: []
docker_socket_path: /var/run/docker.sock
docker_volumes_path: /var/lib/docker/volumes
docker_uid: 1000
docker_gid: 1000

requested_version: {}

port_borgwarehouse: 3000
port_borgwarehouse_ssh: 22223
port_cup: 8800
port_dockge: 5001
port_emby_http: 8096
port_emby_https: 8920
port_komodo_periphery: 8120
port_netalertx: 20211
port_pihole_unbound: 5335
port_portainer_agent: 9001
port_qbittorrent: 48080
port_smartctl_exporter: 9633
port_urbackup_client_fileserver: 35621
port_urbackup_client_discovery: 35622
port_urbackup_client_commands: 35623
port_urbackup_server_fastcgi: 55413
port_urbackup_server_http: 55414
port_urbackup_server_internet_clients: 55415

backupfolders: []

borgmatic_encryption_passphrase: "{{ undef(hint='You must specify the Borgmatic encryption password') }}"
backup_exclude_patterns:
  - "*.log"

cup_control_server: ""
cup_registries: {}
cup_servers: {}

ddns_alias: ""
ddns_aliases: []
ddns_interface: ""
ddns_hostname: ""
ddns_password: ""
ddns_username: ""

kopia_generate_certs: false

netalertx_interface: "{{ undef(hint='You must specify the interface for ARPSCAN') }}"
netalertx_subnet: "{{ undef(hint='You must specify the subnet for ARPSCAN') }}"

pihole_password: "{{ undef(hint='You must specify the PiHole password') }}"
pihole_dns_domain: "home"
pihole_docker_network_3digit: "172.21.200"

smartctlexporter_extra_args: []
