- name: Copy scripts to the host they belong to
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0755"
  loop: "{{ lookup('ansible.builtin.fileglob', inventory_hostname + '/*', wantlist=True) }}"
