apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kopia-missingbackup
spec:
  groups:
    - name: kopia
      rules:
        - alert: KopiaMissingBackup
          annotations:
            description: |
              Kopia has not created a backup of {{ $labels.exported_host }} in the last {{ printf "%.0f" $value }} hours.
            summary: Kopia missing backup.
          expr: (time() - max by (repository) (kopia_go_exporter_backup_end_time)) / 3600 > 25
          for: 1m
          labels:
            severity: warning
