services:
  convertx:
    image: ghcr.io/c4illin/convertx:v0.14.1
    container_name: convertx
    env_file: .env
    labels:
      kompose.volume.type: persistentVolumeClaim
      kompose.volume.size: 5Gi
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./data:/app/data
