apiVersion: v2
# renovate: image=ghcr.io/scanopy/scanopy/server
appVersion: v0.12.9
dependencies:
  - name: common
    version: 29.5.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: scanopy
type: application
version: 1.0.0
