- name: Deploy alloy as docker
  hosts: "{{ groups['docker'] | difference(groups['external']) }}"
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: alloy
    requested_image_version:
      alloy: "grafana/alloy:v1.17.0"
      geoipupdate: "maxmindinc/geoipupdate:v7.1.1"
    docker_compose_create_dirs:
      - name: config
      - name: data
      - name: geoipupdate
    docker_compose_template_files_copy:
      - name: config/config.alloy
