apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: transmute
  name: transmute-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: transmute
          port: 3313
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*"  # allows any origin
      allowMethods:
        - GET
        - POST
        - OPTIONS
      allowHeaders:
        - authorization
        - cache-control
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m"  # preflight requests can be cached for 10 minutes.
    fqdn: transmute.kubernetes.home
    tls:
      secretName: transmute-cert-secret
