apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: karakeep
  name: karakeep-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: karakeep
          port: 3000
  virtualhost:
    fqdn: karakeep.kubernetes.home
    tls:
      secretName: karakeep-cert-secret
