apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: omni-tools
  name: omni-tools-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: omni-tools
          port: 80
  virtualhost:
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*" # allows any origin
      allowMethods:
        - GET
        - POST
        - OPTIONS
      allowHeaders:
        - authorization
        - cache-control
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m" # preflight requests can be cached for 10 minutes.
    fqdn: omni-tools.kubernetes.home
    tls:
      secretName: omni-tools-cert-secret
