apiVersion: v2
# renovate: image=ghcr.io/caglaryalcin/omnisight
appVersion: latest
dependencies:
  - name: common
    version: 28.26.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: omnisight
type: application
version: 1.0.0
