- name: List all repos on the REST API
  hosts: backupserver
  tasks:
    - name: Call the REST API
      ansible.builtin.include_role:
        name: rest-api
      vars:
        rest_api_fact_name: "borgwarehouse_repos"
    - name: Debug URLs
      ansible.builtin.debug:
        msg: "{{ borgwarehouse_repos.json | community.general.json_query('repoList[*].alias') }}"
  vars:
    rest_api_url: "http://localhost:3000"
    rest_api_endpoint: "/api/v1/repositories"
    rest_api_method: "GET"
    rest_api_headers:
      Authorization: "Bearer {{ borgwarehouse_api_key }}"
- name: Deploy borgmatic as docker
  hosts: backupclient
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: borgmatic
    requested_version:
      borgmatic: "2.0.6"
    docker_compose_create_dirs:
      - name: cache
      - name: config
      - name: etc-borgmatic
      - name: repo
    docker_compose_template_files_copy:
      - name: etc-borgmatic/config.yaml
    borgwarehouse_repo_id: "{{ hostvars[groups['backupserver'][0]].borgwarehouse_repos.json.repoList | community.general.json_query('[?alias==`' + inventory_hostname + '`].repositoryName') | first }}"
    docker_ipv6_ipam_subnet: "{{ docker_ipv6_ipam_subnet_borgmatic }}"
