apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-cert
spec:
  secretName: portainer-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - portainer.kubernetes.home
