- name: Copy all required scripts
  hosts: linux
  vars:
    scripts_ownership_user: "{{ ansible_user }}"
    scripts_ownership_group: users
  tasks:
    - name: Copy scripts to the host they belong to
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}"
        owner: "{{ scripts_ownership_user }}"
        group: "{{ scripts_ownership_group }}"
        mode: "0755"
      loop: "{{ lookup('ansible.builtin.fileglob', playbook_dir + '/files/' + inventory_hostname + '/*', wantlist=True, errors='ignore') }}"
    - name: Template scripts to the host they belong to
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
        owner: "{{ scripts_ownership_user }}"
        group: "{{ scripts_ownership_group }}"
        mode: "0755"
      loop: "{{ lookup('ansible.builtin.fileglob', playbook_dir + '/templates/' + inventory_hostname + '/*', wantlist=True, errors='ignore') }}"
