- name: Create beets as docker
  hosts:
    - synology216
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: beets
    docker_compose_create_dirs:
      - config
      - library
    requested_version:
      beets: "2.3.1"
    docker_compose_template_configfiles_copy:
      - config/config.yaml
