- name: Deploy netalertx as docker
  hosts: "{{ groups['dnsserver'][0] | default([]) }}"
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: netalertx
    requested_image_version:
      netalertx: "ghcr.io/jokob-sk/netalertx:25.11.29"
    netalertx_subnet: "{{ network_subnet }}"
