- name: Mount the given entries
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: mounted
    fstype: "{{ item.fstype | default('nfs') }}"
    opts: "{{ item.opts | default('auto,x-systemd.device-timeout=1min,timeo=14,x-systemd.idle-timeout=0,_netdev') }}"
  loop: "{{ fstab_entries }}"
