apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: loki
  name: loki-httpproxy
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: loki-gateway
      port: 80
  virtualhost:
    fqdn: loki.kubernetes.home
    tls:
      secretName: loki-cert-secret
