apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: omni-tools
  name: omni-tools-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: omni-tools
          port: 80
  virtualhost:
    fqdn: omnitools.kubernetes.home
    tls:
      secretName: omni-tools-cert-secret
