apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pkg-exporter-updates
spec:
  groups:
    - name: updates
      rules:
        - alert: RebootRequired
          expr: pkg_reboot_required{host!~"k8s.*"} > 0
          labels:
            severity: warning
          annotations:
            description: 'The host requires a reboot'
            summary: 'Host {{ $labels.host }} running an outdated kernel'
        - alert: UpdatesPending
          expr: |
            sum by (host) (
              pkg_upgradable{host!~"k8s.*"}
            ) > 10
          labels:
            severity: warning
          annotations:
            description: 'The host has at least 10 updates pending'
            summary: 'Host {{ $labels.host }} has {{ $value }} updates pending'
        - alert: UpdatesPendingCritical
          expr: |
            sum by (host) (
              pkg_upgradable{host!~"k8s.*",label=~".*Security.*"}
            ) > 0
          labels:
            severity: critical
          annotations:
            description: 'The host has critical updates pending'
            summary: 'Host {{ $labels.host }} has {{ $value }} critical updates pending'
