apiVersion: v2
# renovate: image=sharevb/it-tools
appVersion: 2025.10.12
dependencies:
  - name: common
    version: 28.26.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: it-tools
type: application
version: 1.0.0
