apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guacamole-cert
spec:
  secretName: guacamole-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - guacamole.kubernetes.home
