- name: Extend bashrc with autocompletions
  hosts: controlserver
  tasks:
    - name: Add autocompletion to bashrc if not already present
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bash_aliases"
        state: present
        line: 'source <({{ item }} completion bash)'
        regexp: '#?\s*source <\({{ item }} completion bash\).*'
      loop:
        - kubectl
        - helm
        - kompose
- name: Extend bashrc with krew path
  hosts: controlserver
  tasks:
    - name: Add krew path to bashrc if not already present
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bash_aliases"
        state: present
        line: 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"'
        regexp: '#?\s*export PATH="\${KREW_ROOT:-\$HOME/\.krew}/bin:\$PATH".*'
