- name: Deploy helm
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "helm/helm:3.21.2"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: helm
    download_url: "https://get.helm.sh/{{ bin_filename }}-v{{ requested_binary_version }}-linux-amd64.tar.gz"
    version_flag: "version --short"
