- name: Deploy kor
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_version: "0.6.8"
    bin_filename: kor
    binary_repository: "yonahd/kor"
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}_Linux_x86_64.tar.gz"
    version_flag: "version"
    decompression_options:
      - "--wildcards"
      - "{{ bin_filename }}*"
