- name: Deploy kubectl
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "kubernetes/kubernetes:1.36.2"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: kubectl
    download_url: "https://dl.k8s.io/release/v{{ requested_binary_version }}/bin/linux/amd64/{{ bin_filename }}"
    compressed: false
    destination_path: "/usr/local/bin/{{ bin_filename }}"
    version_flag: "version"
