- name: Deploy kompose
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "kubernetes/kompose:1.36.0"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: kompose
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}-linux-amd64"
    compressed: false
    destination_path: "/usr/local/bin/{{ bin_filename }}"
    version_flag: "version"
