- name: Deploy kubectl
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_version: "1.32.4"
    bin_filename: kubectl
    binary_repository: "kubernetes/kubernetes"
    download_url: "https://dl.k8s.io/release/v{{ requested_binary_version }}/bin/linux/amd64/{{ bin_filename }}"
    compressed: false
    destination_path: "/usr/local/bin/{{ bin_filename }}"
    version_flag: "version"
