- name: Deploy kompose
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_version: "1.36.0"
    bin_filename: kompose
    binary_repository: "kubernetes/kompose"
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}-linux-amd64"
    compressed: false
    destination_path: "/usr/local/bin/{{ bin_filename }}"
    version_flag: "version"
