- name: Deploy kubetail
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_version: "0.17.0"
    bin_filename: kubetail
    binary_repository: "kubetail-org/kubetail"
    download_url: "https://github.com/{{ binary_repository }}/releases/download/cli/\
          v{{ requested_binary_version }}/{{ bin_filename }}-linux-amd64.tar.gz"
    decompression_options:
      - "--wildcards"
      - "{{ bin_filename }}*"
