- name: Deploy kubectx
  hosts: controlserver
  roles:
    - binary-install
  vars:
    requested_binary_version: "0.11.0"
    bin_filename: kubectx
    binary_repository: "ahmetb/kubectx"
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}_v{{ requested_binary_version }}_linux_x86_64.tar.gz"
    decompression_options:
      - "--wildcards"
      - "{{ bin_filename }}*"
