- name: Deploy kubectl
  ansible.builtin.import_playbook: deploy-kubectl.yaml
- name: Deploy helm
  ansible.builtin.import_playbook: deploy-helm.yaml
- name: Deploy kustomize
  ansible.builtin.import_playbook: deploy-kustomize.yaml
- name: Deploy kompose
  ansible.builtin.import_playbook: deploy-kompose.yaml
- name: Deploy kubeconform
  ansible.builtin.import_playbook: deploy-kubeconform.yaml
- name: Deploy krew
  ansible.builtin.import_playbook: deploy-krew.yaml
- name: Deploy oras
  ansible.builtin.import_playbook: deploy-oras.yaml
- name: Deploy kor
  ansible.builtin.import_playbook: deploy-kor.yaml
- name: Deploy kubetail
  ansible.builtin.import_playbook: deploy-kubetail.yaml
- name: Deploy pluto
  ansible.builtin.import_playbook: deploy-pluto.yaml
- name: Deploy k9s
  ansible.builtin.import_playbook: deploy-k9s.yaml
