# - name: Debug headers
#   ansible.builtin.debug:
#     msg: "{{ rest_api_headers }}"
# - name: Debug body
#   ansible.builtin.debug:
#     msg: "{{ rest_api_data }}"
- name: Call REST API with required parameters
  ansible.builtin.uri:
    url: "{{ rest_api_url }}{{ rest_api_endpoint }}"
    method: "{{ rest_api_method }}"
    headers: "{{ rest_api_headers }}"
    body: "{{ rest_api_data }}"
    body_format: form-urlencoded
    return_content: true
  register: rest_api_response
- name: Set the result in a fact
  ansible.builtin.set_fact:
    rest_api_response: "{{ rest_api_response }}"
# - name: Debug response
#   ansible.builtin.debug:
#     msg: "{{ rest_api_response }}"
