apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: prometheus-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: kube-prometheus-stack-prometheus
          port: 9090
  virtualhost:
    fqdn: prometheus.kubernetes.home
    tls:
      secretName: prometheus-cert-secret
