cephClusterSpec:
  resources:
    mgr:
      requests:
        cpu: "250m"
    mon:
      requests:
        cpu: "250m"
        memory: "1Gi"
    osd:
      requests:
        cpu: "250m"
    prepareosd:
      requests:
        cpu: "150m"
    cleanup:
      requests:
        cpu: "150m"
