cephClusterSpec:
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "k8s-worker-1"
        devices:
          - name: "sdb"
      - name: "k8s-worker-2"
        devices:
          - name: "sdb"
      - name: "k8s-worker-3"
        devices:
          - name: "sdb"
cephFileSystems: {}
cephObjectStores: {}
