- name: Deploy <APP_NAME> as docker
  hosts: <ANSIBLE_HOST>
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: <APP_NAME_LOWERCASE>
    requested_image_version:
      <APP_NAME_LOWERCASE>: "<APP_IMAGE_REPO>:<APP_IMAGE_TAG>"
    docker_compose_create_dirs:
      - name: config
      - name: data
    docker_compose_template_files_copy:
      - name: XXX
