apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dbgate-cert
spec:
  secretName: dbgate-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - dbgate.kubernetes.home
