apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: beszel-cert
spec:
  secretName: beszel-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - beszel.kubernetes.home
