- name: Deploy rustdesk as docker
  hosts: external
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: rustdesk
    requested_version:
      rustdesk: "1.1.14"
- name: Disable Wayland
  become: true
  hosts:
    - htpc
  tasks:
    - name: Disable Wayland in GDM
      ansible.builtin.lineinfile:
        path: /etc/gdm/custom.conf
        regexp: '#WaylandEnable=false'
        line: 'WaylandEnable=false'
        owner: root
        group: root
        mode: '0644'
