apiVersion: v2
# renovate: image=ghcr.io/sergi0g/cup
appVersion: v3.5.1
dependencies:
  - name: common
    version: 28.33.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: cup
type: application
version: 1.0.0
