- name: Deploy Medialyze as docker
  hosts: htpc
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: medialyze
    requested_image_version:
      medialyze: "ghcr.io/frederikemmer/medialyze:0.16.0"
    docker_compose_create_dirs:
      - name: config
