- name: Print the package manager
  ansible.builtin.debug:
    msg: System {{ inventory_hostname }} has package manager {{ ansible_pkg_mgr }}
- name: Remove the requested packages
  become: true
  when: ansible_pkg_mgr == 'apt'
  block:
    - name: Remove packages
      when: ansible_pkg_mgr != 'unknown'
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"
