- name: Generate dynamic configuration for Dockpeek
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate configuration file from template
      ansible.builtin.template:
        src: config/templates/dockpeek-values-config-private.yaml.j2
        dest: "dockpeek-values-config-private.yaml"
