apiVersion: v2
# renovate: image=henrygd/beszel-agent
appVersion: 0.18.1
dependencies:
  - name: common
    version: 28.33.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: beszel-agent
type: application
version: 1.0.0
