- name: Install some packages
  ansible.builtin.include_role:
    name: package-install
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - apparmor
      - apparmor-utils
- name: GPG Dearmor and add Docker repository
  ansible.builtin.include_role:
    name: gpg-dearmor-repo
  vars:
    gpg_project_name: docker-archive-keyring
    gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
    gpg_signed_repo: "https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
- name: Install docker
  ansible.builtin.include_role:
    name: package-install
  vars:
    packages:
      - docker-ce
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
