apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: scanopy
  name: scanopy-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: scanopy
          port: 60072
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    fqdn: scanopy.kubernetes.home
    tls:
      secretName: scanopy-cert-secret
