- name: Deploy Termix as docker
  hosts: control
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: termix
    requested_image_version:
      termix: "ghcr.io/lukegus/termix:release-2.3.1"
      termix-guacd: "guacamole/guacd:latest@sha256:2d266a525a72ad55d8ea7cd4ca8342a1b44075759b03660d8684821b3636a922"
    docker_compose_create_dirs:
      - name: data
