- name: Authenticate to qbittorrent web UI
  hosts:
    - omv
    - synology216
  roles:
    - rest-api
  vars:
    rest_api_url: "http://{{ ansible_host }}:{{ port_qbittorrent }}"
    rest_api_endpoint: "/api/v2/auth/login"
    rest_api_method: "POST"
    rest_api_headers:
      Referer: "http://{{ ansible_host }}:{{ port_qbittorrent }}"
    rest_api_data:
      username: "{{ qbittorrent_username }}"
      password: "{{ qbittorrent_password }}"
- name: Set completion script for torrent completion
  hosts:
    - omv
    - synology216
  roles:
    - rest-api
  vars:
    rest_api_url: "http://{{ ansible_host }}:{{ port_qbittorrent }}"
    rest_api_endpoint: "/api/v2/app/setPreferences"
    rest_api_method: "POST"
    rest_api_headers:
      Cookie: "{{ rest_api_response.cookies_string }}"
      Referer: "http://{{ ansible_host }}:{{ port_qbittorrent }}"
    rest_api_data: 'json={"autorun_enabled": true, "autorun_program": "/bin/bash {{ ansible_user_dir }}/torrent_completed.sh \"%N\""}'
