apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seaweedfs-adminui-cert
spec:
  secretName: seaweedfs-adminui-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - seaweedfs-adminui.kubernetes.home
