apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: borgmatic-missingbackup
spec:
  groups:
    - name: borgmatic
      rules:
        - alert: BorgmaticMissingBackup
          annotations:
            description: |
              Borg has not created a backup of {{ $labels.repository }} in the last {{ printf "%.0f" $value }} hours.
            summary: Borg missing backup.
          expr: (time() - max by (instance, repository) (borg_last_backup_timestamp)) / 3600 > 3*24
          for: 1m
          labels:
            severity: warning
