apiVersion: v2
appVersion: v1.7.2
dependencies:
  - name: common
    version: 28.26.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: dockpeek
type: application
version: 1.0.0
