apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deepflow-cert
spec:
  secretName: deepflow-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - deepflow.kubernetes.home
