apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    k8s-app: vert
  name: vert-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: vert
          port: 80
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    fqdn: vert.kubernetes.home
    tls:
      secretName: vert-cert-secret
