apiVersion: v2
# renovate: image=caronc/apprise
appVersion: 1.0.0
dependencies:
  - name: common
    version: 29.5.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: apprise
type: application
version: 1.0.0
