grafana:
  deploymentStrategy:
    type: Recreate
  persistence:
    enabled: true
  additionalDataSources:
    - name: Loki
      access: proxy
      isDefault: false
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: Home
      orgId: 1
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local/

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: host
          action: replace
