- name: Generate dynamic configuration for Prometheus
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate configuration file from template
      ansible.builtin.template:
        src: config/templates/prometheus-values-config-private.yaml.j2
        dest: "prometheus-values-config-private.yaml"
