- name: Install git
  hosts: controlserver
  become: true
  roles:
    - package-install
  vars:
    packages:
      - git
- name: Set up identity
  hosts: controlserver
  tasks:
    - name: Set name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_name }}"
    - name: Set email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"
- name: Add some aliases for git
  hosts: controlserver
  tasks:
    - name: Add alias for status
      community.general.git_config:
        name: alias.st
        scope: global
        value: status
    - name: Add alias for checkout
      community.general.git_config:
        name: alias.co
        scope: global
        value: checkout
    - name: Add alias for branch
      community.general.git_config:
        name: alias.br
        scope: global
        value: branch
    - name: Add alias for listing ignored files
      community.general.git_config:
        name: alias.lsig
        scope: global
        value: "ls-files --others --ignored --exclude-standard"
- name: install pre-commit package
  hosts: controlserver
  tasks:
    - name: install pre-commit via pipx
      community.general.pipx:
        name: pre-commit
        state: present
