apiVersion: v2
# renovate: image=operacle/checkcle
appVersion: v1.6.0
dependencies:
  - name: common
    version: 28.26.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: checkcle
type: application
version: 1.0.0
