---
- name: Copy and set-up send_push script
  template:
    src: send_push.sh.j2
    dest: "{{ user_home }}/send_push.sh"
    mode: 0755
- name: Copy and set-up pushover.info file
  template:
    src: pushover.info.j2
    dest: "{{ user_home }}/pushover.info"
    mode: 0744
- name: Copy sink.d script for push notifications on OMV
  template:
    src: OMV_send_push.j2
    dest: /usr/share/openmediavault/notification/sink.d/send_push
    mode: 0755
  when: inventory_hostname == "omv"
- name: Copy push php script on Synology
  copy:
    src: synology-pushover.php
    dest: /volume1/web/synology-pushover.php
    mode: 0755
  when: inventory_hostname == "syno"
