- name: Deploy inadyn as docker
  hosts:
    - standalone
    - external
  roles:
    - role: docker-compose
      when: ddns_aliases | length > 0
  vars:
    docker_compose_projectname: inadyn
    requested_version:
      inadyn: "2.12.0"
    docker_compose_template_files_copy:
      - name: config/inadyn.conf
