- name: Create inadyn as docker
  hosts:
    - control
    - torrents
    - htpc
    - synology
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: inadyn
    requested_version:
      inadyn: "2.12.0"
    docker_compose_template_files_copy:
      - name: config/inadyn.conf
- name: Create ddclient as docker
  hosts:
    - external
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: ddclient
    requested_version:
      ddclient: "4.0.0"
    docker_compose_template_files_copy:
      - name: config/ddclient.conf
