apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dockpeek-cert
spec:
  secretName: dockpeek-cert-secret
  issuerRef:
    name: contour-selfsigned-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - dockpeek.kubernetes.home
