apiVersion: v2
# renovate: image=eitchtee/wygiwyh
appVersion: 0.19.0
dependencies:
  - name: common
    version: 29.5.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: wygiwyh
type: application
version: 1.0.0
