- name: Comment out Proxmox enterprise repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: ^[^#]
    line: '# \1'
    backrefs: true
    state: present
- name: Comment out Proxmox ceph repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: ^[^#]
    line: '# \1'
    backrefs: true
    state: present
- name: Add Proxmox community repo
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
    filename: pve-no-subscription
    state: present
