apiVersion: v2
# renovate: image=ghcr.io/pouzor/homelable-backend
appVersion: 1.0.0
dependencies:
  - name: common
    version: 28.33.4
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: homelable
type: application
version: 1.0.0
