- name: Disable Wayland
  become: true
  hosts:
    - htpc
  tasks:
    - name: Disable Wayland in GDM
      ansible.builtin.lineinfile:
        path: /etc/gdm3/custom.conf
        regexp: '#WaylandEnable=false'
        line: 'WaylandEnable=false'
        owner: root
        group: root
        mode: '0644'
