- name: Deploy node-exporter as a service
  hosts: proxmox
  roles:
    - binary-install
  vars:
    requested_binary_repo_version: "prometheus/node_exporter:1.10.2"
    binary_repository: "{{ requested_binary_repo_version.split(':')[0] }}"
    requested_binary_version: "{{ requested_binary_repo_version.split(':')[1] }}"
    bin_filename: node_exporter
    service_name: node-exporter
    download_url: "https://github.com/{{ binary_repository }}/releases/download/\
          v{{ requested_binary_version }}/{{ bin_filename }}-{{ requested_binary_version }}.linux-amd64.tar.gz"
- name: Deploy node-exporter as docker
  hosts: docker
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: node-exporter
    requested_image_version:
      node-exporter: "quay.io/prometheus/node-exporter:v1.10.2"
