apiVersion: v2
# renovate: image=louislam/uptime-kuma
appVersion: 2.2.1
dependencies:
  - name: common
    version: 29.5.5
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
name: uptimekuma
type: application
version: 1.0.0
