global:
  seaweedfs:
    enableSecurity: true

allInOne:
  enabled: true
  data:
    type: "persistentVolumeClaim"
  s3:
    enabled: true
    enableAuth: true
    httpsPort: 8334

admin:
  enabled: true
  masters: seaweedfs-all-in-one:9333
master:
  enabled: false
volume:
  enabled: false
filer:
  enabled: false
worker:
  enabled: false
