workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DD_WATCHER_CONTROL_HOST: 192.168.31.54
            DD_WATCHER_CONTROL_PORT: 2375
            DD_WATCHER_HTPC_HOST: 192.168.31.157
            DD_WATCHER_HTPC_PORT: 2375
            DD_WATCHER_OMV_HOST: 192.168.31.66
            DD_WATCHER_OMV_PORT: 2375
            DD_WATCHER_PIHOLE_HOST: 192.168.31.2
            DD_WATCHER_PIHOLE_PORT: 2375
            DD_WATCHER_QOTOM_HOST: 192.168.31.4
            DD_WATCHER_QOTOM_PORT: 2375
            DD_WATCHER_PIDASH_HOST: 192.168.31.235
            DD_WATCHER_PIDASH_PORT: 2375
            DD_WATCHER_VPS_HOST: 138.199.210.40
            DD_WATCHER_VPS_PORT: 2375
            DD_WATCHER_SYNOLOGY216_HOST: 192.168.31.138
            DD_WATCHER_SYNOLOGY216_PORT: 2375
            DD_WATCHER_SYNOLOGY224_HOST: 192.168.31.177
            DD_WATCHER_SYNOLOGY224_PORT: 2375
