- name: Generate dynamic configuration for Drydock
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate configuration file from template
      ansible.builtin.template:
        src: config/templates/drydock-values-config-private.yaml.j2
        dest: "drydock-values-config-private.yaml"
