- name: Deploy ntopng as docker
  hosts: networkmonitoring
  roles:
    - docker-compose
  vars:
    docker_compose_projectname: ntopng
    requested_image_version:
      ntopng: "ntop/ntopng:latest"
      valkey: "docker.io/valkey/valkey:9.1.0"
    docker_compose_create_dirs:
      - name: ntopng
      - name: redis
